JWT_ALGORYTHM = "HS256"
POSTGRES_TIMEOUT = 60
DEFAULT_HTTP_TIMEOUT = 20

LOGGING_SENSITIVE_FIELDS = (
)

LOGGING_SENSITIVE_REPLACEMENT = "******"

LOGGING_DISABLED_ENDPOINTS = ("/metrics",)
DEFAULT_LANGUAGE = "en"


ROCKET_CAPACITY_DEFAULT = 3
ROCKET_CAPACITY_OFFLINE = 6
ROCKET_CAPACITY_PREMIUM = 4

REFERRAL_PREFIX = "pilot_"
BOT_NAME = "CryptoRockets_Bot"
WEBAPP_NAME = "launch"


MAX_BALANCE = 50
WHEEL_TIMEOUT = 60 * 3
WHEEL_AD_TIMEOUT = 60
ROCKET_TIMEOUT_DEFAULT = 60 * 6
ROCKET_TIMEOUT_OFFLINE = 60
ROCKET_TIMEOUT_PREMIUM = 60 * 24


FUEL_CAPACITY_MAP = {
    "default": ROCKET_CAPACITY_DEFAULT,
    "offline": ROCKET_CAPACITY_OFFLINE,
    "premium": ROCKET_CAPACITY_PREMIUM,
}
