"""init

Revision ID: 0001
Revises: 
Create Date: 2025-05-26 21:42:36.851832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=True),
    sa.Column('tg_first_name', sa.String(), nullable=True),
    sa.Column('tg_last_name', sa.String(), nullable=True),
    sa.Column('tg_is_premium', sa.Boolean(), nullable=True),
    sa.Column('tg_language_code', sa.String(), nullable=True),
    sa.Column('tg_photo_url', sa.String(), nullable=True),
    sa.Column('bot_banned', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
