"""refactor timeouts

Revision ID: 0002
Revises: 0001
Create Date: 2025-06-13 21:08:05.017949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('next_default_rocket_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('next_offline_rocket_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('next_premium_rocket_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('next_wheel_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('next_wheel_ad_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'default_rocket_received')
    op.drop_column('users', 'wheel_received')
    op.drop_column('users', 'premium_rocket_received')
    op.drop_column('users', 'offline_rocket_received')
    op.drop_column('users', 'wheel_ad_received')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wheel_ad_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('offline_rocket_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('premium_rocket_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('wheel_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('default_rocket_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users', 'next_wheel_ad_at')
    op.drop_column('users', 'next_wheel_at')
    op.drop_column('users', 'next_premium_rocket_at')
    op.drop_column('users', 'next_offline_rocket_at')
    op.drop_column('users', 'next_default_rocket_at')
    # ### end Alembic commands ###
