"""add fk on user

Revision ID: 0003
Revises: 0002
Create Date: 2025-06-15 15:57:35.607489

"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ads', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_ads_user_id'), 'ads', ['user_id'], unique=False)
    op.create_foreign_key('ads_users_fk', 'ads', 'users', ['user_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ads_users_fk', 'ads', type_='foreignkey')
    op.drop_index(op.f('ix_ads_user_id'), table_name='ads')
    op.alter_column('ads', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
