"""refactor has_spins

Revision ID: 0004
Revises: 0003
Create Date: 2025-06-15 16:04:32.744347

"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spin_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'has_spins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_spins', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'spin_count')
    # ### end Alembic commands ###
