"""add last_online

Revision ID: 0007
Revises: 0006
Create Date: 2025-06-17 17:38:09.265606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_online', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.execute("update users set last_online = updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_online')
    # ### end Alembic commands ###
