"""add offline_rocket_received

Revision ID: 0009
Revises: 0008
Create Date: 2025-06-10 19:33:29.868336

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("offline_rocket_received", postgresql.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
    )
    op.add_column(
        "users", sa.Column("wheel_received", postgresql.TIMESTAMP(), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "wheel_received")
    op.drop_column("users", "offline_rocket_received")
    # ### end Alembic commands ###
