"""refactor gifts

Revision ID: 0010
Revises: 0009
Create Date: 2025-06-18 22:11:50.279727

"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts_users', sa.Column('collection_id', sa.BigInteger(), nullable=True))
    op.alter_column('gifts_users', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_gifts_users_collection_id'), 'gifts_users', ['collection_id'], unique=False)
    op.create_foreign_key('gifts_users_collections_fkey', 'gifts_users', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gifts_users_collections_fkey', 'gifts_users', type_='foreignkey')
    op.drop_index(op.f('ix_gifts_users_collection_id'), table_name='gifts_users')
    op.alter_column('gifts_users', 'transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('gifts_users', 'collection_id')
    # ### end Alembic commands ###
