"""add seen

Revision ID: 0010
Revises: 0009
Create Date: 2025-06-10 20:52:28.680897

"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rockets', sa.Column('seen', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rockets', 'seen')
    # ### end Alembic commands ###
