"""yet another rocket refactor

Revision ID: 0011
Revises: 0010
Create Date: 2025-06-10 21:49:05.862604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_rocket_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('premium_rocket_received', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_rocket_received')
    op.drop_column('users', 'default_rocket_received')
    # ### end Alembic commands ###
