"""boost_balance

Revision ID: 0013
Revises: 0012
Create Date: 2025-06-19 14:09:29.301276

"""
from alembic import op
import sqlalchemy as sa


revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('boost_balance', sa.Numeric(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'boost_balance')
    # ### end Alembic commands ###
