"""refactor tasks

Revision ID: 0014
Revises: 0013
Create Date: 2025-06-12 22:56:05.719481

"""
import sqlalchemy as sa
from alembic import op

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks_users", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks_users", "status")
    # ### end Alembic commands ###
