"""add rolls

Revision ID: 0014
Revises: 0013
Create Date: 2025-06-19 14:23:29.447538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0014'
down_revision = '0013'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rolls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ton_amount', sa.Numeric(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rolls_user_id'), 'rolls', ['user_id'], unique=False)
    op.add_column('gifts_users', sa.Column('roll_id', sa.Integer(), nullable=False))
    op.drop_constraint('gifts_users_transaction_id_fkey', 'gifts_users', type_='foreignkey')
    op.create_foreign_key('gifts_users_rolls_fkey', 'gifts_users', 'rolls', ['roll_id'], ['id'])
    op.drop_column('gifts_users', 'transaction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts_users', sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('gifts_users_rolls_fkey', 'gifts_users', type_='foreignkey')
    op.create_foreign_key('gifts_users_transaction_id_fkey', 'gifts_users', 'transactions', ['transaction_id'], ['id'])
    op.drop_column('gifts_users', 'roll_id')
    op.drop_index(op.f('ix_rolls_user_id'), table_name='rolls')
    op.drop_table('rolls')
    # ### end Alembic commands ###
