"""add is boost

Revision ID: 0015
Revises: 0014
Create Date: 2025-06-19 19:51:47.763777

"""
from alembic import op
import sqlalchemy as sa


revision = '0015'
down_revision = '0014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets_config', sa.Column('is_boost', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets_config', 'is_boost')
    # ### end Alembic commands ###
