"""add wheel_amount

Revision ID: 0016
Revises: 0015
Create Date: 2025-06-13 16:05:47.750658

"""
from alembic import op
import sqlalchemy as sa


revision = '0016'
down_revision = '0015'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('wheel_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'wheel_amount')
    # ### end Alembic commands ###
