"""add gift_id_ton

Revision ID: 0018
Revises: 0017
Create Date: 2025-06-20 15:20:08.024373

"""
from alembic import op
import sqlalchemy as sa


revision = '0018'
down_revision = '0017'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('gift_id_ton', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'gifts', ['gift_id_ton'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gifts', type_='unique')
    op.drop_column('gifts', 'gift_id_ton')
    # ### end Alembic commands ###
