"""refactor gifts

Revision ID: 0020
Revises: 0019
Create Date: 2025-06-21 17:25:56.069535

"""
from alembic import op
import sqlalchemy as sa


revision = '0020'
down_revision = '0019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gifts_users', 'collection_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_gifts_users_collection_id'), 'gifts_users', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gifts_users_collection_id'), table_name='gifts_users')
    op.alter_column('gifts_users', 'collection_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
