"""refactor gifts

Revision ID: 0021
Revises: 0020
Create Date: 2025-06-21 18:18:10.178482

"""
from alembic import op
import sqlalchemy as sa


revision = '0021'
down_revision = '0020'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gifts_users', 'collection_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gifts_users', 'collection_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
