"""add profit

Revision ID: 0023
Revises: 0022
Create Date: 2025-06-22 11:02:42.671916

"""
from alembic import op
import sqlalchemy as sa


revision = '0023'
down_revision = '0022'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets_config', sa.Column('profit', sa.Boolean(), server_default='true', nullable=False))
    op.create_index(op.f('ix_bets_config_collection_id'), 'bets_config', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_config_collection_id'), table_name='bets_config')
    op.drop_column('bets_config', 'profit')
    # ### end Alembic commands ###
