"""add released_for_usd

Revision ID: 0025
Revises: 0024
Create Date: 2025-06-24 20:37:34.831727

"""
from alembic import op
import sqlalchemy as sa


revision = '0025'
down_revision = '0024'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts_users', sa.Column('released_for_usd', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gifts_users', 'released_for_usd')
    # ### end Alembic commands ###
