"""add rich_ads_tasks

Revision ID: 0026
Revises: 0025
Create Date: 2025-06-25 18:33:03.724950

"""
from alembic import op
import sqlalchemy as sa


revision = '0026'
down_revision = '0025'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rich_ads_tasks', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rich_ads_tasks')
    # ### end Alembic commands ###
